@startuml WebAppNavigationDiagram

hide stereotype
hide circle
left to right direction



Package "LoggedOut" {
    
    Login : /login
    Register : /register

    Login <--> Register : Innlogging/Registrering

}

Package "LoggedIn" {

    Home : /home
    Tasks : /tasks
    TaskDetail : /tasks/<task_id>
    Medication : /medication
    MedicationDay : /medication/<medication_id>
    MedicationDose : /medication/<medication_id>/<dose_id>
    AutoDoorLock : /lock_control


    Home <--> AutoDoorLock : Tilbake/Dørlås

    Home <--> Tasks : Tilbake/Huskeliste

    Tasks <--> TaskDetail : Tilbake/Oppgave
    Home <-> Medication : Tilbake/Medisiner
    Medication <--> MedicationDay : Tilbake/Dag
    MedicationDay <--> MedicationDose : Tilbake/Dose

}

Root : /

Root --> Login : Logget ut
Root --> Home : Logget inn


Login <--> Home : Logg ut/Logg inn
